# Generated by Django 4.2.16 on 2024-11-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('origen', models.CharField(max_length=1)),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('cod_plantel', models.CharField(max_length=50)),
                ('institucion_educativa', models.CharField(max_length=255)),
                ('anio_curso', models.CharField(max_length=10)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('extra_curricular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.actividadextracurricular')),
                ('voceria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.voceria')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'db_table': 'feveem"."asistente',
                'managed': True,
            },
        ),
    ]
