# Generated by Django 5.0.7 on 2024-11-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
        ('feveem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='extra_curricular',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.actividadextracurricular'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asistente',
            unique_together={('cedula', 'origen')},
        ),
    ]
