# Generated by Django 5.0.7 on 2024-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feveem', '0004_asistente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
