# Generated by Django 4.2.16 on 2024-11-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Actividad extra curricular',
                'verbose_name_plural': 'Actividades extra curriculares',
                'db_table': 'auxiliares"."actividad_extra_curricular',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Voceria',
                'verbose_name_plural': 'Vocerias',
                'db_table': 'auxiliares"."voceria',
                'managed': True,
            },
        ),
    ]
