# Generated by Django 5.0.7 on 2024-09-29 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0002_area_clasificacion_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Plantel',
                'verbose_name_plural': 'Planteles',
                'db_table': 'reportes"."plantel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_femenino', models.IntegerField(blank=True, null=True, verbose_name='Femenino')),
                ('cantidad_masculino', models.IntegerField(blank=True, null=True, verbose_name='Masculino')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.clasificacion')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personales',
                'db_table': 'reportes"."personal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_femenino', models.IntegerField(blank=True, null=True, verbose_name='Femenino')),
                ('cantidad_masculino', models.IntegerField(blank=True, null=True, verbose_name='Masculino')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total')),
                ('dia', models.IntegerField(verbose_name='Día')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.nivel')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'reportes"."estudiante',
                'managed': True,
                'unique_together': {('director', 'nivel', 'cantidad_femenino', 'cantidad_masculino', 'total', 'dia', 'mes', 'anio')},
            },
        ),
    ]
