# Generated by Django 5.0.7 on 2024-09-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': False, 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'managed': False, 'verbose_name': 'Personal', 'verbose_name_plural': 'Personales'},
        ),
    ]
