# Generated by Django 5.0.7 on 2024-09-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0002_area_clasificacion_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=1, verbose_name='Origen')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('codigo_plantel', models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo Plantel')),
                ('tipo_cargo', models.CharField(max_length=255)),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('numero_cuenta', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'personal"."docente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AreaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_areas', to='auxiliares.areaformacion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_personal', to='personal.docente')),
            ],
            options={
                'verbose_name': 'Area Personal',
                'verbose_name_plural': 'Areas Personal',
                'db_table': 'personal"."area_personal',
                'managed': True,
            },
        ),
    ]
